services:
  - type: worker
    name: ff-calendar-discord-bot
    runtime: docker
    rootDir: legacy
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: CALENDAR_TZ
        value: Europe/Oslo
      - key: NEWS_CHANNEL_NAME
        value: news
      - key: DATABASE_URL
        sync: false
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: NEWS_CHANNEL_ID
        sync: false
      - key: GUILD_ID
        sync: false
      - key: ADMIN_USER_IDS
        sync: false
